In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import os
from tqdm import tqdm
import numpy as np

In [2]:
%%time
main_data_df = pd.read_csv('./prepped_data/main_data_ver_6.csv')
print(main_data_df.shape)
main_data_df.head()

(1350728, 15)
Wall time: 3.3 s

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1

In [3]:
addr_df = pd.read_csv('./prepped_data/addr_data_ver_1.csv')
print(addr_df.shape)
addr_df.head()

(572321, 2)

                   지번주소                도로명주소
0   서울특별시 종로구 청운동 144-3  서울특별시 종로구 자하문로 94-0
1  서울특별시 종로구 청운동 108-14  서울특별시 종로구 자하문로 96-0
2  서울특별시 종로구 청운동 108-13  서울특별시 종로구 자하문로 98-0
3   서울특별시 종로구 청운동 134-2  서울특별시 종로구 자하문로 99-3
4   서울특별시 종로구 청운동 130-2  서울특별시 종로구 자하문로 99-4

In [4]:
addr_df2 = pd.read_csv('./prepped_data/additional_addr_1.csv')
print(addr_df2.shape)
addr_df2.head()

(33720, 2)

                    지번주소                 도로명주소
0   서울특별시 강남구 청담동 129-16  서울특별시 강남구 압구정로79길 72
1     서울특별시 강서구 공항동 49-1   서울특별시 강서구 공항대로 18-1
2   서울특별시 노원구 상계동 341-15      서울특별시 노원구 상계로 90
3   서울특별시 동대문구 용두동 236-4     서울특별시 동대문구 왕산로 52
4  서울특별시 영등포구 당산동2가 15-2   서울특별시 영등포구 영등포로 112

In [5]:
addr_df2 = addr_df2.dropna()
print(addr_df2.shape)

(7594, 2)

In [6]:
addr_df = pd.concat([addr_df, addr_df2]).drop_duplicates(subset=['지번주소']).reset_index(drop=True)
print(addr_df.shape)
addr_df.head()

(579915, 2)

                   지번주소                도로명주소
0   서울특별시 종로구 청운동 144-3  서울특별시 종로구 자하문로 94-0
1  서울특별시 종로구 청운동 108-14  서울특별시 종로구 자하문로 96-0
2  서울특별시 종로구 청운동 108-13  서울특별시 종로구 자하문로 98-0
3   서울특별시 종로구 청운동 134-2  서울특별시 종로구 자하문로 99-3
4   서울특별시 종로구 청운동 130-2  서울특별시 종로구 자하문로 99-4

In [7]:
merge_df = main_data_df.merge(addr_df, on=['지번주소'])
print(merge_df.shape)
merge_df.head()

(1304288, 16)

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무,도로명주소
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0

In [8]:
coor_df = pd.read_csv('./prepped_data/coor_data_ver_1.csv')
print(coor_df.shape)
coor_df.head()

(546319, 3)

                 도로명주소            X좌표           Y좌표
0  서울특별시 종로구 자하문로 94-0  953241.683263  1.954023e+06
1  서울특별시 종로구 자하문로 96-0  953243.258151  1.954034e+06
2  서울특별시 종로구 자하문로 98-0  953240.877646  1.954055e+06
3  서울특별시 종로구 자하문로 99-3  953195.459364  1.954079e+06
4  서울특별시 종로구 자하문로 99-4  953193.346779  1.954097e+06

In [9]:
merge_df['구'] = merge_df['지번주소'].apply(lambda x: x.split(' ')[1])
merge_df['동'] = merge_df['지번주소'].apply(lambda x: x.split(' ')[2])
merge_df['로'] = merge_df['도로명주소'].apply(lambda x: x.split(' ')[2])

In [48]:
merge_df['동'].nunique()

443

In [10]:
merge_df['동'].unique()

array(['대치동', '도곡동', '삼성동', '역삼동', '천호동', '공릉동', '신대방동', '가락동', '방이동',
       '신천동', '여의도동', '응암동', '망우동', '우이동', '영등포동8가', '황학동', '마포동', '신정동',
       '오류동', '전농동', '목동', '봉천동', '휘경동', '성내동', '시흥동', '양평동4가', '고척동',
       '쌍문동', '방배동', '상봉동', '개포동', '논현동', '수서동', '청담동', '강일동', '길동',
       '명일동', '암사동', '번동', '수유동', '가양동', '공항동', '등촌동', '방화동', '염창동',
       '화곡동', '남현동', '신림동', '광장동', '구의동', '자양동', '중곡동', '화양동', '가리봉동',
       '개봉동', '구로동', '신도림동', '가산동', '독산동', '상계동', '월계동', '중계동', '하계동',
       '방학동', '창동', '답십리동', '신설동', '용두동', '이문동', '장안동', '제기동', '노량진동',
       '대방동', '사당동', '공덕동', '노고산동', '대흥동', '도화동', '동교동', '상수동', '상암동',
       '서교동', '성산동', '신공덕동', '아현동', '염리동', '합정동', '대현동', '북가좌동', '연희동',
       '창천동', '충정로2가', '충정로3가', '합동', '홍은동', '서초동', '양재동', '잠원동', '도선동',
       '마장동', '상왕십리동', '성수동1가', '성수동2가', '옥수동', '용답동', '하왕십리동', '행당동',
       '동선동1가', '동선동4가', '동소문동4가', '동소문동6가', '보문동2가', '삼선동5가', '성북동1가',
       '장위동', '하월곡동', '거여동', '문정동', '석촌동', '송파동', '오금동', '잠실동', '신월동',
       '당산동', '당산동2가', '당산동3가', '당산동4가', '당산동5가', '당산동6가', '대림동', '도림동',
       '문래동3가', '문래동5가', '문래동6가', '신길동', '양평동2가', '양평동3가', '양평동5가',
       '영등포동1가', '영등포동2가', '영등포동3가', '영등포동4가', '영등포동5가', '영등포동6가',
       '영등포동7가', '갈월동', '동자동', '문배동', '서계동', '용산동5가', '원효로1가', '원효로3가',
       '한강로1가', '한강로2가', '한강로3가', '한남동', '후암동', '녹번동', '대조동', '불광동',
       '신사동', '역촌동', '견지동', '경운동', '관철동', '구기동', '낙원동', '내수동', '돈의동',
       '부암동', '사직동', '수송동', '숭인동', '신문로1가', '연건동', '연지동', '운니동', '원남동',
       '익선동', '인사동', '인의동', '적선동', '종로1가', '창신동', '충신동', '평창동', '필운동',
       '효제동', '광희동1가', '만리동1가', '만리동2가', '신당동', '오장동', '을지로2가', '을지로3가',
       '을지로5가', '을지로6가', '을지로7가', '의주로1가', '장충동2가', '중림동', '충무로3가',
       '충무로5가', '필동1가', '흥인동', '면목동', '묵동', '신내동', '자곡동', '둔촌동', '미아동',
       '능동', '연남동', '우면동', '금호동4가', '마천동', '영등포동', '구산동', '홍지동', '중화동',
       '군자동', '중동', '창전동', '동선동3가', '석관동', '정릉동', '세곡동', '종암동', '양평동1가',
       '원효로2가', '남대문로5가', '순화동', '도봉동', '상도동', '삼전동', '당산동1가', '진관동',
       '남가좌동', '송정동', '갈현동', '저동2가', '회기동', '북아현동', '홍익동', '돈암동', '교북동',
       '을지로4가', '고덕동', '마곡동', '상도1동', '보문동7가', '청파동3가', '일원동', '상일동',
       '내발산동', '외발산동', '궁동', '온수동', '항동', '청량리동', '동작동', '본동', '흑석동',
       '구수동', '당인동', '망원동', '신수동', '용강동', '하중동', '현석동', '대신동', '천연동',
       '홍제동', '반포동', '금호동1가', '금호동2가', '금호동3가', '사근동', '응봉동', '길음동',
       '동선동2가', '동선동5가', '동소문동1가', '동소문동7가', '보문동1가', '보문동4가', '보문동5가',
       '보문동6가', '삼선동1가', '삼선동2가', '삼선동3가', '삼선동4가', '상월곡동', '성북동',
       '안암동2가', '안암동3가', '안암동4가', '안암동5가', '풍납동', '문래동1가', '양평동6가',
       '동빙고동', '보광동', '산천동', '서빙고동', '신계동', '신창동', '용문동', '용산동2가',
       '용산동3가', '원효로4가', '이촌동', '이태원동', '주성동', '청파동1가', '청파동2가', '효창동',
       '수색동', '증산동', '가회동', '계동', '누상동', '누하동', '동숭동', '명륜1가', '명륜2가',
       '명륜3가', '무악동', '신교동', '신영동', '옥인동', '원서동', '이화동', '창성동', '청운동',
       '통인동', '평동', '행촌동', '혜화동', '홍파동', '효자동', '남창동', '장충동1가', '회현동1가',
       '개화동', '신촌동', '영천동', '옥천동', '신원동', '남영동', '명륜4가', '삼청동', '송월동',
       '신문로2가', '체부동', '예장동', '필동2가', '필동3가', '안암동1가', '남산동2가', '쌍림동',
       '토정동', '내곡동', '보문동3가', '통의동', '광희동2가', '무학동', '묵정동', '염곡동', '천왕동',
       '봉원동', '회현동2가', '냉천동', '안국동', '화동', '율현동', '동소문동2가', '동소문동3가',
       '권농동', '사간동', '소격동', '종로6가', '팔판동', '미근동', '내자동', '청암동', '와룡동',
       '재동', '동소문동5가', '남산동1가', '원지동', '관수동', '관훈동', '당주동', '묘동', '봉익동',
       '종로4가', '종로5가', '남대문로2가', '남대문로3가', '남대문로4가', '다동', '명동2가', '방산동',
       '북창동', '인현동1가', '인현동2가', '입정동', '저동1가', '주교동', '초동', '충무로1가',
       '충무로4가', '예지동', '종로2가', '종로3가', '예관동', '충무로2가', '태평로2가', '명동1가',
       '산림동', '서소문동', '소공동', '수하동', '문래동2가', '문래동4가', '장사동', '정동', '교남동',
       '남산동3가', '서린동', '중학동', '청진동', '수표동', '을지로1가', '남학동', '남대문로1가',
       '장교동', '오곡동', '공평동', '장지동', '궁정동', '삼각동'], dtype=object)

In [49]:
merge_df.drop(columns=['로', '로2'], inplace=True)

In [50]:
merge_df.head()

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무,도로명주소,구,동
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동

In [51]:
merge_coor_df = merge_df.merge(coor_df, on=['도로명주소'])
print(merge_coor_df.shape)
merge_coor_df.head()

(1175640, 20)

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무,도로명주소,구,동,X좌표,Y좌표
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동,960554.893362,1.945193e+06
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동,960554.893362,1.945193e+06
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동,960554.893362,1.945193e+06
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동,960554.893362,1.945193e+06
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0,강남구,대치동,960554.893362,1.945193e+06

In [52]:
%%time
merge_coor_df.to_csv('./prepped_data/main_data_ver_7.csv', index=False)

Wall time: 8.5 s