In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import os
from tqdm import tqdm
import numpy as np

In [2]:
%%time
main_data_df = pd.read_csv('./prepped_data/main_data_ver_6.csv')
print(main_data_df.shape)
main_data_df.head()

(1350728, 15)
Wall time: 3.29 s

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1

In [3]:
addr_df = pd.read_csv('./prepped_data/addr_data_ver_1.csv')
print(addr_df.shape)
addr_df.head()

(572321, 2)

                   지번주소                도로명주소
0   서울특별시 종로구 청운동 144-3  서울특별시 종로구 자하문로 94-0
1  서울특별시 종로구 청운동 108-14  서울특별시 종로구 자하문로 96-0
2  서울특별시 종로구 청운동 108-13  서울특별시 종로구 자하문로 98-0
3   서울특별시 종로구 청운동 134-2  서울특별시 종로구 자하문로 99-3
4   서울특별시 종로구 청운동 130-2  서울특별시 종로구 자하문로 99-4

In [5]:
merge_df = main_data_df.merge(addr_df, on=['지번주소'], how='left')
print(merge_df.shape)
merge_df.head()

(1350728, 16)

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무,도로명주소
0,서울특별시 강남구 대치동 891-23,201302,8,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
1,서울특별시 강남구 대치동 891-23,201303,21,"23,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
2,서울특별시 강남구 대치동 891-23,201305,2,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
3,서울특별시 강남구 대치동 891-23,201306,3,"22,000",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0
4,서울특별시 강남구 대치동 891-23,201306,11,"22,500",2004.0,아파트,43.39,대,일반상업지역,지정되지않음,상업기타,평지,부정형,소로각지,1,서울특별시 강남구 선릉로90길 56-0

In [6]:
nan_df = merge_df[merge_df['도로명주소'].isna()]
print(nan_df.shape)
nan_df.head()

(65256, 16)

,지번주소,계약년월,계약일,거래금액(만원),건축년도,주택유형,토지면적,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,건물유무,도로명주소
11526,서울특별시 강남구 청담동 129-16,201305,25,"270,000",2009.0,오피스텔,218.06,대,일반상업지역,제3종일반주거지역,상업기타,평지,세로장방,광대소각,1,NaN
11527,서울특별시 강남구 청담동 129-16,202008,5,"380,000",2009.0,오피스텔,218.06,대,일반상업지역,제3종일반주거지역,상업기타,평지,세로장방,광대소각,1,NaN
11528,서울특별시 강남구 청담동 129-16,202008,5,"379,900",2009.0,오피스텔,218.06,대,일반상업지역,제3종일반주거지역,상업기타,평지,세로장방,광대소각,1,NaN
14975,서울특별시 강서구 공항동 49-1,201307,5,"13,100",2011.0,오피스텔,45.05,대,준주거지역,근린상업지역,상업용,평지,사다리형,광대로한면,1,NaN
14976,서울특별시 강서구 공항동 49-1,201406,16,"13,500",2011.0,오피스텔,45.05,대,준주거지역,근린상업지역,상업용,평지,사다리형,광대로한면,1,NaN

In [7]:
nan_df['지번주소'].nunique()

33720

In [8]:
nan_df['주택유형'].value_counts()

토지         36958
단독         17776
다가구         4972
연립다세대       3718
제1종근린생활      704
오피스텔         702
제2종근린생활      233
판매           160
숙박            20
업무             6
기타             4
교육연구           3
Name: 주택유형, dtype: int64

In [9]:
addr_to_download_df = nan_df[['지번주소']].drop_duplicates()
print(addr_to_download_df.shape)
addr_to_download_df.head()

(33720, 1)

                        지번주소
11526   서울특별시 강남구 청담동 129-16
14975     서울특별시 강서구 공항동 49-1
29089   서울특별시 노원구 상계동 341-15
33654   서울특별시 동대문구 용두동 236-4
58725  서울특별시 영등포구 당산동2가 15-2

In [10]:
addr_to_download_df.to_csv('./prepped_data/addr_to_download.csv', index=False)