In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
import datetime
import time
tqdm.tqdm.pandas()

In [2]:
new_df = pd.read_excel('./공공주택찾기/강원도/LH_거래사례_20180101_20220224.xlsx')
new_df = new_df.drop(columns=[
    '일괄계약', '도로명', '시군구', '본번', '부번', '건물연식'
])
print(new_df.shape)
new_df.head()

(222, 10)

,지번주소,건물(단지)명,전용면적(㎡),거래금액(만원),층,건축년도,계약날짜,단가(만원/㎡),부동산유형,소유자
0,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,5,2021,2021-08-17,249.910449,연립다세대,LH
1,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,5,2021,2021-08-17,249.910449,연립다세대,LH
2,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15300,4,2021,2021-08-17,254.908658,연립다세대,LH
3,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15300,4,2021,2021-08-17,254.908658,연립다세대,LH
4,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15300,4,2021,2021-08-17,254.908658,연립다세대,LH

In [3]:
concat_df = new_df.copy().sort_values(['지번주소', '건축년도', '부동산유형', '계약날짜', '전용면적(㎡)', '층']).reset_index(drop=True)
print(concat_df.shape)
concat_df.head()

(222, 10)

,지번주소,건물(단지)명,전용면적(㎡),거래금액(만원),층,건축년도,계약날짜,단가(만원/㎡),부동산유형,소유자
0,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH
1,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH
2,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH
3,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH
4,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH

In [4]:
concat_df['계약날짜'] = pd.to_datetime(concat_df['계약날짜'])

In [5]:
from_2019_df = concat_df.copy()

In [6]:
from_2019_df['전용면적(㎡)_최소'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '전용면적(㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('min')['전용면적(㎡)']
from_2019_df['전용면적(㎡)_평균'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '전용면적(㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('mean')['전용면적(㎡)']
from_2019_df['전용면적(㎡)_최대'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '전용면적(㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('max')['전용면적(㎡)']
from_2019_df['전용면적(㎡)_합'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '전용면적(㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('sum')['전용면적(㎡)']

In [7]:
from_2019_df['거래금액(만원)_최소'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '거래금액(만원)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('min')['거래금액(만원)']
from_2019_df['거래금액(만원)_평균'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '거래금액(만원)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('mean')['거래금액(만원)']
from_2019_df['거래금액(만원)_최대'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '거래금액(만원)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('max')['거래금액(만원)']
from_2019_df['거래금액(만원)_합'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '거래금액(만원)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('sum')['거래금액(만원)']

In [8]:
from_2019_df['층_최대'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '층']].groupby(['지번주소', '건축년도', '부동산유형']).transform('max')['층']

In [9]:
from_2019_df['단가(만원/㎡)_최소'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '단가(만원/㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('min')['단가(만원/㎡)']
from_2019_df['단가(만원/㎡)_평균'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '단가(만원/㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('mean')['단가(만원/㎡)']
from_2019_df['단가(만원/㎡)_최대'] = from_2019_df[['지번주소', '건축년도', '부동산유형', '단가(만원/㎡)']].groupby(['지번주소', '건축년도', '부동산유형']).transform('max')['단가(만원/㎡)']

In [10]:
from_2019_df.head()

,지번주소,건물(단지)명,전용면적(㎡),거래금액(만원),층,건축년도,계약날짜,단가(만원/㎡),부동산유형,소유자,전용면적(㎡)_최소,전용면적(㎡)_평균,전용면적(㎡)_최대,전용면적(㎡)_합,거래금액(만원)_최소,거래금액(만원)_평균,거래금액(만원)_최대,거래금액(만원)_합,층_최대,단가(만원/㎡)_최소,단가(만원/㎡)_평균,단가(만원/㎡)_최대
0,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH,60.0215,60.0215,60.0215,2881.032,15000,15150.0,15300,727200,5,249.910449,252.409553,254.908658
1,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH,60.0215,60.0215,60.0215,2881.032,15000,15150.0,15300,727200,5,249.910449,252.409553,254.908658
2,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH,60.0215,60.0215,60.0215,2881.032,15000,15150.0,15300,727200,5,249.910449,252.409553,254.908658
3,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH,60.0215,60.0215,60.0215,2881.032,15000,15150.0,15300,727200,5,249.910449,252.409553,254.908658
4,강원도 강릉시 포남동 1169-0,(1169-0),60.0215,15000,2,2021,2021-08-17,249.910449,연립다세대,LH,60.0215,60.0215,60.0215,2881.032,15000,15150.0,15300,727200,5,249.910449,252.409553,254.908658

In [11]:
summary_df = from_2019_df.drop(columns=['전용면적(㎡)', '거래금액(만원)', '층', '단가(만원/㎡)']).drop_duplicates()
summary_df['구'] = summary_df['지번주소'].apply(lambda x: x.split(' ')[1])
summary_df['동'] = summary_df['지번주소'].apply(lambda x: x.split(' ')[2])
summary_df = summary_df.sort_values(['구', '동', '계약날짜', '지번주소', '부동산유형']).reset_index(drop=True)
summary_df = summary_df.drop(columns=['구', '동'])
print(summary_df.shape)
summary_df.head()

(6, 18)

,지번주소,건물(단지)명,건축년도,계약날짜,부동산유형,소유자,전용면적(㎡)_최소,전용면적(㎡)_평균,전용면적(㎡)_최대,전용면적(㎡)_합,거래금액(만원)_최소,거래금액(만원)_평균,거래금액(만원)_최대,거래금액(만원)_합,층_최대,단가(만원/㎡)_최소,단가(만원/㎡)_평균,단가(만원/㎡)_최대
0,강원도 강릉시 포남동 1172-14,(1172-14),2020,2020-08-24,연립다세대,LH,55.4200,55.456000,55.4800,2218.240,14050,14335.000000,14650,573400,5,253.244412,258.493117,264.059120
1,강원도 강릉시 포남동 1180-0,(1180-0),2020,2020-11-19,연립다세대,LH,55.4200,58.316939,83.8100,2857.530,15300,16070.408163,21550,787450,5,257.129221,276.534113,280.584626
2,강원도 강릉시 포남동 1169-0,(1169-0),2021,2021-08-17,연립다세대,LH,60.0215,60.021500,60.0215,2881.032,15000,15150.000000,15300,727200,5,249.910449,252.409553,254.908658
3,강원도 원주시 우산동 297-3,(297-3),2021,2022-01-13,오피스텔,LH,41.2200,41.306500,41.5600,1652.260,12163,12605.500000,12663,504220,4,292.661213,305.178277,306.684427
4,강원도 원주시 우산동 297-13,(297-13),2021,2022-01-27,오피스텔,LH,42.0400,42.145882,42.4000,716.480,13713,14189.470588,14263,241221,4,323.419811,336.685659,338.547353

In [12]:
concat_df['지번주소'].nunique()

6

In [13]:
%%time
summary_df.to_excel('./공공주택찾기/강원도/LH_거래사례_요약_동별계약날짜순정렬_20180101_20220224.xlsx', index=False)

Wall time: 16 ms