In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('단독다가구(전월세)_실거래가_20210117204243.csv', encoding='euc-kr', header=15)
print(df.shape)
df.head()

(126722, 11)

,시군구,번지,도로조건,계약면적(㎡),전월세구분,계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,12m미만,13.20,월세,202010,30,300,29,1991.0,논현로8길
1,서울특별시 강남구 개포동,1***,25m이상,15.00,전세,202011,2,"10,000",0,1989.0,논현로
2,서울특별시 강남구 개포동,1***,-,15.12,전세,202012,23,"9,000",0,1989.0,NaN
3,서울특별시 강남구 개포동,1***,8m미만,16.50,월세,202010,9,"1,000",40,1990.0,개포로15길
4,서울특별시 강남구 개포동,1***,8m미만,16.50,월세,202011,10,"2,000",35,NaN,개포로15길