In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [2]:
basedir = './국토교통부_실거래가_공개시스템/단독다가구매매/'
filenames = [f for f in os.listdir(basedir) if (f.endswith('.csv'))&('(' in f)]#&('실거래가' in f)]
filenames

['단독다가구(매매)_실거래가_20130101_20131231.csv',
 '단독다가구(매매)_실거래가_20140101_20141231.csv',
 '단독다가구(매매)_실거래가_20150101_20151231.csv',
 '단독다가구(매매)_실거래가_20160101_20161231.csv',
 '단독다가구(매매)_실거래가_20170101_20171231.csv',
 '단독다가구(매매)_실거래가_20180101_20181231.csv',
 '단독다가구(매매)_실거래가_20190101_20191231.csv',
 '단독다가구(매매)_실거래가_20200101_20201231.csv',
 '단독다가구(매매)_실거래가_20210101_20210325.csv']

In [3]:
for i, f in enumerate(filenames):
    print(i)
    chunk = pd.read_csv(basedir + f, chunksize=1, encoding='euc-kr', header=15)
    df = next(chunk)
    if '해제사유발생일' in df.columns.tolist():
        df = df.drop(columns=['해제사유발생일'])
        
    print(df.shape)
    display(df.head())
    
    if i == 0:
        first_cols = df.columns
    else:
        print(sum(df.columns == first_cols))

0
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993,논현로138길

1
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,다가구,8m미만,171.69,116.9,201412,31,"70,000",1989,논현로6길

11
2
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1**,다가구,8m미만,192.3,130.3,201508,31,"103,000",1988,선릉로12길

11
3
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,다가구,8m미만,225.72,116.9,201604,25,"101,000",1990,논현로6길

11
4
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1**,다가구,8m미만,192.96,130.6,201709,16,"168,500",1987,선릉로12길

11
5
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,다가구,8m미만,406.82,178.9,201806,15,"185,000",1995,논현로8길

11
6
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,단독,8m미만,247.65,175.5,201904,2,"165,000",1988,논현로6길

11
7
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,다가구,8m미만,415.33,180,202003,13,"260,000",1991,논현로18길

11
8
(1, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 개포동,1***,단독,8m미만,498.42,540.1,202101,7,"820,000",1997,개포로31길

11

In [4]:
dfs_list = []
for i, f in tqdm(enumerate(filenames)):
    df = pd.read_csv(basedir + f, encoding='euc-kr', header=15)
    if '해제사유발생일' in df.columns.tolist():
        df = df.drop(columns=['해제사유발생일'])
    
    dfs_list.append(df)

9it [00:00, 42.78it/s]

In [5]:
concat_df = pd.concat(dfs_list).reset_index(drop=True)
print(concat_df.shape)
concat_df.head()

(108904, 11)

,시군구,번지,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993.0,논현로138길
1,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길
2,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길
3,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길
4,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길

In [6]:
concat_df['주택유형'].value_counts()

단독     75641
다가구    33263
Name: 주택유형, dtype: int64

In [7]:
concat_df.isna().sum()

시군구            0
번지             0
주택유형           0
도로조건           0
연면적(㎡)         0
대지면적(㎡)        0
계약년월           0
계약일            0
거래금액(만원)       0
건축년도         560
도로명         5756
dtype: int64

In [8]:
land_specs_df = pd.read_csv('./prepped_data/land_specs_ver_4.csv')
print(land_specs_df.shape)
land_specs_df.head()

(8706295, 11)

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0

In [9]:
land_specs_df['번지'] = land_specs_df['지번주소'].apply(lambda x: x.split(' ')[3])

In [10]:
land_specs_df['본번'] = land_specs_df['번지'].apply(lambda x: x.split('-')[0])

In [11]:
land_specs_df.head()

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0,100-0,100
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0,100-0,100
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0,100-0,100
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0,100-0,100
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0,100-0,100

In [12]:
def masking(x):
    # x is a string
    
    if pd.isna(x) == True:
        return x
    else:
        mask = ''
        for i in range(len(x)-1):
            mask += '*'
        
        return x[0] + mask

In [13]:
land_specs_df['본번_masked'] = land_specs_df['본번'].apply(masking)

In [14]:
land_specs_df.head()

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0,100-0,100,1**
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0,100-0,100,1**
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0,100-0,100,1**
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0,100-0,100,1**
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0,100-0,100,1**

In [15]:
land_specs_df['시군구'] = land_specs_df['지번주소'].apply(lambda x: x.split(' ')[0])\
+ ' ' + land_specs_df['지번주소'].apply(lambda x: x.split(' ')[1])\
+ ' ' + land_specs_df['지번주소'].apply(lambda x: x.split(' ')[2])

In [16]:
concat_df.rename(columns={'번지':'본번_masked'}, inplace=True)

In [17]:
concat_df.head()

,시군구,본번_masked,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993.0,논현로138길
1,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길
2,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길
3,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길
4,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길

In [18]:
land_specs_df.head()

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked,시군구
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0,100-0,100,1**,서울특별시 강남구 개포동
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0,100-0,100,1**,서울특별시 강남구 개포동
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0,100-0,100,1**,서울특별시 강남구 개포동
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0,100-0,100,1**,서울특별시 강남구 개포동
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0,100-0,100,1**,서울특별시 강남구 개포동

In [19]:
concat_df['도로조건'].value_counts()

8m미만     92151
12m미만    11662
25m미만     3193
25m이상     1256
-          642
Name: 도로조건, dtype: int64

In [20]:
land_specs_df['도로접면'].value_counts()

세로한면(가)    2688474
지정되지않음     1289408
세로한면(불)    1008484
세로각지(가)     726127
소로한면        627975
소로각지        503622
광대소각        428623
중로각지        393928
중로한면        298912
광대로한면       278183
맹지          185238
광대세각        171918
세로각지(불)     105268
Name: 도로접면, dtype: int64

In [21]:
not_assigned_df = land_specs_df[land_specs_df['도로접면'] == '지정되지않음']
print(not_assigned_df.shape)
not_assigned_df.head()

(1289408, 15)

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked,시군구
93,서울특별시 강남구 개포동 1055-11,2013,도로,170.0,자연녹지지역,지정되지않음,도로등,지정되지않음,지정되지않음,지정되지않음,321000.0,1055-11,1055,1***,서울특별시 강남구 개포동
94,서울특별시 강남구 개포동 1055-11,2014,도로,170.0,자연녹지지역,지정되지않음,도로등,지정되지않음,지정되지않음,지정되지않음,323400.0,1055-11,1055,1***,서울특별시 강남구 개포동
95,서울특별시 강남구 개포동 1055-11,2015,도로,170.0,자연녹지지역,지정되지않음,도로등,지정되지않음,지정되지않음,지정되지않음,330000.0,1055-11,1055,1***,서울특별시 강남구 개포동
96,서울특별시 강남구 개포동 1055-11,2016,도로,170.0,자연녹지지역,지정되지않음,도로등,지정되지않음,지정되지않음,지정되지않음,341500.0,1055-11,1055,1***,서울특별시 강남구 개포동
97,서울특별시 강남구 개포동 1055-11,2017,도로,170.0,자연녹지지역,지정되지않음,도로등,지정되지않음,지정되지않음,지정되지않음,351400.0,1055-11,1055,1***,서울특별시 강남구 개포동

In [22]:
not_assigned_df['용도지역명1'].value_counts()

제2종일반주거지역    573481
제3종일반주거지역    205302
제1종일반주거지역    143216
일반상업지역        97845
자연녹지지역        80545
개발제한구역        76911
준주거지역         47502
준공업지역         40090
제1종전용주거지역     12022
근린상업지역         5813
생산녹지지역         4185
중심상업지역         2144
유통상업지역          265
제2종전용주거지역        47
보전녹지지역           40
Name: 용도지역명1, dtype: int64

In [23]:
not_assigned_df['지목명'].value_counts()

도로       875423
대        172966
하천        59593
구거        33646
전         25275
공원        23678
임야        22893
철도용지      19794
잡종지       19111
답         15204
제방        12629
수도용지       2716
학교용지       1596
주차장        1451
유지          984
사적지         900
묘지          372
공장용지        320
종교용지        291
체육용지        267
과수원         154
유원지          81
주유소용지        35
창고용지         29
Name: 지목명, dtype: int64

In [24]:
def doro_condition(x):
    if pd.isna(x) == True:
        return x
    else:
        if '광대' in x:
            return '25m이상'
        elif '중로' in x:
            return '25m미만'
        elif '소로' in x:
            return '12m미만'
        elif '세로' in x:
            return '8m미만'
        else:
            return '-'

In [25]:
land_specs_df['도로조건'] = land_specs_df['도로접면'].apply(doro_condition)

In [26]:
land_specs_df['도로조건'].value_counts()

8m미만     4528353
-        1474646
12m미만    1131597
25m이상     878724
25m미만     692840
Name: 도로조건, dtype: int64

In [27]:
land_specs_df.head()

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked,시군구,도로조건
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0,100-0,100,1**,서울특별시 강남구 개포동,-
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0,100-0,100,1**,서울특별시 강남구 개포동,-
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0,100-0,100,1**,서울특별시 강남구 개포동,-
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0,100-0,100,1**,서울특별시 강남구 개포동,-
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0,100-0,100,1**,서울특별시 강남구 개포동,-

In [28]:
concat_df.head()

,시군구,본번_masked,주택유형,도로조건,연면적(㎡),대지면적(㎡),계약년월,계약일,거래금액(만원),건축년도,도로명
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993.0,논현로138길
1,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길
2,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길
3,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길
4,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길

In [29]:
concat_df['년'] = concat_df['계약년월'].apply(lambda x: int(str(x)[:4]))

In [30]:
concat_df.rename(columns={'대지면적(㎡)':'토지면적'}, inplace=True)

In [31]:
concat_df.head()

,시군구,본번_masked,주택유형,도로조건,연면적(㎡),토지면적,계약년월,계약일,거래금액(만원),건축년도,도로명,년
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993.0,논현로138길,2013
1,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길,2013
2,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길,2013
3,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길,2013
4,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길,2013

In [32]:
dandok_df = land_specs_df[land_specs_df['토지이동상황'] == '단독']
print(dandok_df.shape)
dandok_df.head()

(2587553, 16)

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked,시군구,도로조건
1004,서울특별시 강남구 개포동 1166-7,2013,대,249.8,제2종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가),3200000.0,1166-7,1166,1***,서울특별시 강남구 개포동,8m미만
1005,서울특별시 강남구 개포동 1166-7,2014,대,249.8,제2종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가),3300000.0,1166-7,1166,1***,서울특별시 강남구 개포동,8m미만
1006,서울특별시 강남구 개포동 1166-7,2015,대,249.8,제2종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가),3420000.0,1166-7,1166,1***,서울특별시 강남구 개포동,8m미만
1022,서울특별시 강남구 개포동 1166-9,2013,대,249.6,제2종일반주거지역,지정되지않음,단독,평지,세로장방,세로각지(가),3390000.0,1166-9,1166,1***,서울특별시 강남구 개포동,8m미만
1023,서울특별시 강남구 개포동 1166-9,2014,대,249.6,제2종일반주거지역,지정되지않음,단독,평지,세로장방,세로각지(가),3498000.0,1166-9,1166,1***,서울특별시 강남구 개포동,8m미만

In [33]:
merge_df = concat_df.merge(dandok_df, on=['시군구', '본번_masked', '토지면적', '도로조건', '년'])
print(merge_df.shape)
merge_df.head()

(795326, 23)

,시군구,본번_masked,주택유형,도로조건,연면적(㎡),토지면적,계약년월,계약일,거래금액(만원),건축년도,도로명,년,지번주소,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번
0,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길,2013,서울특별시 강남구 논현동 124-11,대,제3종일반주거지역,지정되지않음,단독,평지,사다리형,세로한면(가),4170000.0,124-11,124
1,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길,2013,서울특별시 강남구 논현동 74-13,대,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로각지(가),4000000.0,74-13,74
2,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길,2013,서울특별시 강남구 논현동 111-35,대,제3종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가),4260000.0,111-35,111
3,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길,2013,서울특별시 강남구 논현동 214-9,대,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로한면(가),4550000.0,214-9,214
4,서울특별시 강남구 논현동,1**,다가구,8m미만,421.48,205.9,201303,7,"164,000",1993.0,봉은사로11길,2013,서울특별시 강남구 논현동 173-11,대,제2종일반주거지역,지정되지않음,단독,평지,정방형,세로각지(가),4110000.0,173-11,173

In [34]:
merge_df['용도지역명1'].value_counts()

제2종일반주거지역    581238
제1종일반주거지역     92215
제3종일반주거지역     74353
준주거지역         28608
준공업지역          8203
제1종전용주거지역      6101
일반상업지역         2590
근린상업지역         1074
개발제한구역          687
자연녹지지역          257
Name: 용도지역명1, dtype: int64

In [35]:
concat_df.head()

,시군구,본번_masked,주택유형,도로조건,연면적(㎡),토지면적,계약년월,계약일,거래금액(만원),건축년도,도로명,년
0,서울특별시 강남구 논현동,8*,다가구,8m미만,329.78,165.4,201305,24,"177,500",1993.0,논현로138길,2013
1,서울특별시 강남구 논현동,1**,다가구,8m미만,335.90,171.4,201312,18,"173,500",1990.0,학동로12길,2013
2,서울특별시 강남구 논현동,7*,다가구,8m미만,435.32,177.2,201304,23,"138,000",1992.0,논현로146길,2013
3,서울특별시 강남구 논현동,1**,다가구,8m미만,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길,2013
4,서울특별시 강남구 논현동,2**,다가구,8m미만,401.33,193.8,201305,21,"179,000",1997.0,논현로124길,2013

In [36]:
merge_df.rename(columns={'연면적(㎡)':'연면적'}, inplace=True)

In [37]:
land_specs_df.head()

,지번주소,년,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,공시지가,번지,본번,본번_masked,시군구,도로조건
0,서울특별시 강남구 개포동 100-0,2013,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,325000.0,100-0,100,1**,서울특별시 강남구 개포동,-
1,서울특별시 강남구 개포동 100-0,2014,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,330000.0,100-0,100,1**,서울특별시 강남구 개포동,-
2,서울특별시 강남구 개포동 100-0,2015,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,335000.0,100-0,100,1**,서울특별시 강남구 개포동,-
3,서울특별시 강남구 개포동 100-0,2016,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,345000.0,100-0,100,1**,서울특별시 강남구 개포동,-
4,서울특별시 강남구 개포동 100-0,2017,전,876.0,자연녹지지역,지정되지않음,전,완경사,부정형,맹지,355000.0,100-0,100,1**,서울특별시 강남구 개포동,-

In [38]:
selected_cols = ['지번주소', '주택유형', '연면적', '토지면적', '계약년월', '계약일', '거래금액(만원)', '건축년도', '도로명']
ls_cols = [col for col in land_specs_df.columns if col not in ['지번주소', '년', '토지면적', '번지', '본번', '본번_masked', '시군구', '도로조건', '공시지가']]
ls_cols

['지목명', '용도지역명1', '용도지역명2', '토지이동상황', '지형높이', '지형형상', '도로접면']

In [39]:
selected_df = merge_df[selected_cols + ls_cols]
print(selected_df.shape)
selected_df.head()

(795326, 16)

,지번주소,주택유형,연면적,토지면적,계약년월,계약일,거래금액(만원),건축년도,도로명,지목명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면
0,서울특별시 강남구 논현동 124-11,다가구,335.90,171.4,201312,18,"173,500",1990.0,학동로12길,대,제3종일반주거지역,지정되지않음,단독,평지,사다리형,세로한면(가)
1,서울특별시 강남구 논현동 74-13,다가구,435.32,177.2,201304,23,"138,000",1992.0,논현로146길,대,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로각지(가)
2,서울특별시 강남구 논현동 111-35,다가구,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길,대,제3종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가)
3,서울특별시 강남구 논현동 214-9,다가구,401.33,193.8,201305,21,"179,000",1997.0,논현로124길,대,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로한면(가)
4,서울특별시 강남구 논현동 173-11,다가구,421.48,205.9,201303,7,"164,000",1993.0,봉은사로11길,대,제2종일반주거지역,지정되지않음,단독,평지,정방형,세로각지(가)

In [40]:
selected_df['주택유형'].value_counts()

단독     540860
다가구    254466
Name: 주택유형, dtype: int64

In [41]:
selected_df['지목명'].value_counts()

대       794126
임야         289
전          279
도로         189
종교용지       155
잡종지        123
답           47
철도용지        43
구거          19
사적지         16
제방          16
묘지          14
주차장          5
하천           4
공장용지         1
Name: 지목명, dtype: int64

In [42]:
selected_df = selected_df[selected_df['지목명'] == '대'].drop(columns=['지목명']).reset_index(drop=True)

In [43]:
selected_df.head()

,지번주소,주택유형,연면적,토지면적,계약년월,계약일,거래금액(만원),건축년도,도로명,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면
0,서울특별시 강남구 논현동 124-11,다가구,335.90,171.4,201312,18,"173,500",1990.0,학동로12길,제3종일반주거지역,지정되지않음,단독,평지,사다리형,세로한면(가)
1,서울특별시 강남구 논현동 74-13,다가구,435.32,177.2,201304,23,"138,000",1992.0,논현로146길,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로각지(가)
2,서울특별시 강남구 논현동 111-35,다가구,347.10,181.9,201308,28,"169,000",1991.0,선릉로135길,제3종일반주거지역,지정되지않음,단독,평지,세로장방,세로한면(가)
3,서울특별시 강남구 논현동 214-9,다가구,401.33,193.8,201305,21,"179,000",1997.0,논현로124길,제3종일반주거지역,지정되지않음,단독,평지,가로장방,세로한면(가)
4,서울특별시 강남구 논현동 173-11,다가구,421.48,205.9,201303,7,"164,000",1993.0,봉은사로11길,제2종일반주거지역,지정되지않음,단독,평지,정방형,세로각지(가)

In [44]:
%%time
selected_df.to_csv(basedir + '단독다가구_매매_20130101_20210325.csv', index=False)

Wall time: 3.03 s