In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
font = {'size': 16}
matplotlib.rc('font', **font)
tqdm.tqdm.pandas()

In [2]:
%%time
main_data_df = pd.read_csv('./Prepped Data/main_data_coor_days_20211223.csv')
print(main_data_df.shape)
main_data_df.head()

<string>:2: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.

(5097504, 22)
Wall time: 11.2 s

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준
0,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,2253,12,12.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-02-22,4070
1,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,730,10,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-04-26,4133
2,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,1815,4,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-08-31,4260
3,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3865,17,11.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-03-29,4470
4,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3062,7,9.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-07-14,4577

In [4]:
main_data_df['건물단지명_키워드'] = main_data_df['건물단지명_키워드'].fillna('없음')

In [5]:
main_data_df.isna().sum()

시군구                   0
번지                    2
본번                    0
부번                    0
건물/단지명                0
거래유형                  0
전용면적(㎡)              36
거래/보증금(만원)            0
월세(만원)                0
층                 17650
건축년도              11687
도로명                   0
부동산유형                 0
가격범위                  0
건물단지명_키워드             0
브랜드                   0
대장구분명                 0
지목                    0
x좌표                   0
y좌표                   0
계약날짜                  0
계약날짜일수_2006년기준        0
dtype: int64

In [6]:
main_data_df = main_data_df.dropna().reset_index(drop=True)
print(main_data_df.shape)
main_data_df.head()

(5068169, 22)

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준
0,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,2253,12,12.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-02-22,4070
1,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,730,10,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-04-26,4133
2,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,1815,4,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-08-31,4260
3,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3865,17,11.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-03-29,4470
4,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3062,7,9.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-07-14,4577

In [7]:
%%time
main_data_df.to_csv('./Prepped Data/main_data_coor_days_nonan_20211224.csv', index=False)

Wall time: 28.1 s