In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
font = {'size': 16}
matplotlib.rc('font', **font)
tqdm.tqdm.pandas()
import numba

In [2]:
%%time
main_data_df = pd.read_csv('./Prepped Data/main_data_new_building_merge_land_specs_20211228.csv', dtype={1:'str', 9:'Int64', 10:'Int64'})
#main_data_df = next(main_data_df)
main_data_df['계약날짜'] = pd.to_datetime(main_data_df['계약날짜'])
main_data_df = main_data_df.sort_values(['시군구', '본번', '부번', '대장구분명', '건축년도', '부동산유형', '계약날짜'])
print(main_data_df.shape)
main_data_df.head()

(5006836, 33)
Wall time: 25.5 s

,시군구,지번,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준,지번주소,토지일련번호,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,데이터기준일자
0,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,매매,33.18,15900,0,1,1992,개포로109길 9,아파트,14000~16000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-03,2,서울특별시 강남구 개포동 12,5864,대,121040.4,제3종일반주거지역,지정되지않음,아파트,평지,부정형,광대소각,2021-07-29
1,서울특별시 강남구 개포동,12,12,0,삼익대청아파트,매매,39.53,24800,0,5,1992,개포로109길 21,아파트,24000~26000,삼익대청,기타,일반,대,206607.181143,443586.061143,2006-01-07,6,서울특별시 강남구 개포동 12,5864,대,121040.4,제3종일반주거지역,지정되지않음,아파트,평지,부정형,광대소각,2021-07-29
2,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,매매,39.53,24700,0,12,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,서울특별시 강남구 개포동 12,5864,대,121040.4,제3종일반주거지역,지정되지않음,아파트,평지,부정형,광대소각,2021-07-29
3,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,매매,49.86,33300,0,11,1992,개포로109길 9,아파트,32000~34000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,서울특별시 강남구 개포동 12,5864,대,121040.4,제3종일반주거지역,지정되지않음,아파트,평지,부정형,광대소각,2021-07-29
4,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,매매,39.53,24700,0,4,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-10,9,서울특별시 강남구 개포동 12,5864,대,121040.4,제3종일반주거지역,지정되지않음,아파트,평지,부정형,광대소각,2021-07-29

In [3]:
main_data_df['지번주소'] = main_data_df['시군구'] + ' ' + main_data_df['지번'] + ' ' + main_data_df['건축년도'].astype('str') + ' ' + main_data_df['부동산유형'] + ' ' + main_data_df['거래유형']

In [4]:
main_data_df['거래유형'].value_counts()

매매    2065298
전세    1982727
월세     958811
Name: 거래유형, dtype: int64

In [5]:
main_data_df['distance_x'] = np.nan
main_data_df['distance_y'] = np.nan
main_data_df['distance'] = np.nan

In [6]:
main_data_df['거래/보증금(만원)'].describe()

count    5.006836e+06
mean     3.056585e+04
std      3.083686e+04
min      0.000000e+00
25%      1.230000e+04
50%      2.300000e+04
75%      3.900000e+04
max      1.850000e+06
Name: 거래/보증금(만원), dtype: float64

In [7]:
main_data_df['계약날짜'].std()

Timedelta('1497 days 16:54:01.654263040')

In [8]:
main_data_df['계약날짜'].describe()

c:\users\max6296\ml\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  """Entry point for launching an IPython kernel.

count                 5006836
unique                   5814
top       2020-06-13 00:00:00
freq                     3202
first     2006-01-01 00:00:00
last      2021-12-01 00:00:00
Name: 계약날짜, dtype: object

In [9]:
dir(main_data_df['x좌표'])

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_convert',
 '_convert_dtypes',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_hidden_attrs',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'progress_apply',
 'progress_map',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [10]:
def year_circular_sine_func(x):
    return math.sin(2*math.pi*((x)/365))

def year_circular_cosine_func(x):
    return math.cos(2*math.pi*((x)/365))

In [11]:
main_data_df['건축년도'].value_counts()

2003    300832
2002    284446
2004    278358
2005    177366
2008    176479
1988    175953
2001    169452
2000    165053
1999    156144
2012    142601
2011    134697
1997    132844
2013    131171
1993    130794
1992    127954
2014    127171
2006    124343
2016    124269
1998    120227
2007    116580
1986    113139
1994    111121
1996    108876
2015    107877
1991    100427
2009     98544
1995     98523
2010     97996
1987     96700
2017     95362
2018     85221
1989     78447
2019     76580
1990     65562
2020     51993
1983     42051
1985     34569
1984     33876
1982     32637
1978     31615
1979     25976
1980     22445
2021     21611
1981     21451
1976     10919
1977     10566
1974      9556
1971      8139
1975      7942
1973      3598
1970      2096
1972      1555
1969      1141
1968       877
1965       383
1966       287
1961       124
1967       123
1956        94
1964        39
1963        29
1962         8
1959         8
1960         7
1940         5
1925         5
1955         1
1942         1
Name: 건축년도, dtype: Int64

In [12]:
'''main_data_df = main_data_df.sample(frac=0.01).reset_index(drop=True)
print(main_data_df.shape)
main_data_df.head()'''

'main_data_df = main_data_df.sample(frac=0.01).reset_index(drop=True)\nprint(main_data_df.shape)\nmain_data_df.head()'

In [16]:
ranges_list = [1000]

numerical_cols = [
    '전용면적(㎡)', '거래/보증금(만원)', '월세(만원)', '층', '건축년도', 'x좌표', 'y좌표', '계약날짜', '계약날짜일수_2006년기준',
    '토지면적'
]

numerical_description_features_list = [
    'mean', 'std', 'min', 'quantile(0.25)', 'quantile(0.5)', 'quantile(0.75)', 'max', 'sum', 'sem', 'skew', 'var'
]

date_offset_months = 12

In [18]:
all_numerical_feature_cols = []
for target_range in ranges_list:
    for col in numerical_cols:
        for f in numerical_description_features_list:
            col_name = '최근{}개월_'.format(date_offset_months) + str(target_range) + '미터이내_' + col + '_' + f
            main_data_df[col_name] = np.nan
            all_numerical_feature_cols.append(col_name)

c:\users\max6296\ml\lib\site-packages\ipykernel_launcher.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

['최근12개월_1000미터이내_전용면적(㎡)_mean',
 '최근12개월_1000미터이내_전용면적(㎡)_std',
 '최근12개월_1000미터이내_전용면적(㎡)_min',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.25)',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.5)',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.75)',
 '최근12개월_1000미터이내_전용면적(㎡)_max',
 '최근12개월_1000미터이내_전용면적(㎡)_sum',
 '최근12개월_1000미터이내_전용면적(㎡)_sem',
 '최근12개월_1000미터이내_전용면적(㎡)_skew']

In [19]:
print(len(all_numerical_feature_cols))
all_numerical_feature_cols[:10]

110

['최근12개월_1000미터이내_전용면적(㎡)_mean',
 '최근12개월_1000미터이내_전용면적(㎡)_std',
 '최근12개월_1000미터이내_전용면적(㎡)_min',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.25)',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.5)',
 '최근12개월_1000미터이내_전용면적(㎡)_quantile(0.75)',
 '최근12개월_1000미터이내_전용면적(㎡)_max',
 '최근12개월_1000미터이내_전용면적(㎡)_sum',
 '최근12개월_1000미터이내_전용면적(㎡)_sem',
 '최근12개월_1000미터이내_전용면적(㎡)_skew']

In [20]:
@numba.jit
def numerical_description_feature_creator(x, y):

    if y == 'mean':
        return x.mean()
    elif y == 'std':
        return x.std()
    elif y == 'min':
        return x.min()
    elif y == 'quantile(0.25)':
        return x.quantile(0.25)
    elif y == 'quantile(0.5)':
        return x.quantile(0.5)
    elif y == 'quantile(0.75)':
        return x.quantile(0.75)
    elif y == 'max':
        return x.max()
    elif y == 'sum':
        return x.sum()
    elif y == 'sem':
        return x.sem()
    elif y == 'skew':
        return x.skew()
    elif y == 'var':
        return x.var()
    else:
        raise ValueError('feature name error')

In [13]:
@numba.jit
def temp_func(df):
    import pandas as pd
    import numpy as np
    
    df = df.copy()
    
    ranges_list = [1000]
    
    numerical_cols = ['전용면적(㎡)', '거래/보증금(만원)', '월세(만원)', '층', '건축년도', 'x좌표', 'y좌표', '계약날짜', '계약날짜일수_2006년기준', '토지면적']
    
    numerical_description_features_list = [
        'mean', 'std', 'min', 'quantile(0.25)', 'quantile(0.5)', 'quantile(0.75)', 'max', 'sum', 'sem', 'skew', 'var'
    ]
    
    date_offset_months = 12    
    
    all_numerical_feature_cols = []
    for target_range in ranges_list:
        for col in numerical_cols:
            for f in numerical_description_features_list:
                col_name = '최근{}개월_'.format(date_offset_months) + str(target_range) + '미터이내_' + col + '_' + f
                df[col_name] = np.nan
                all_numerical_feature_cols.append(col_name)
    
    def numerical_description_feature_creator(x, y):
    
        if y == 'mean':
            return x.mean()
        elif y == 'std':
            return x.std()
        elif y == 'min':
            return x.min()
        elif y == 'quantile(0.25)':
            return x.quantile(0.25)
        elif y == 'quantile(0.5)':
            return x.quantile(0.5)
        elif y == 'quantile(0.75)':
            return x.quantile(0.75)
        elif y == 'max':
            return x.max()
        elif y == 'sum':
            return x.sum()
        elif y == 'sem':
            return x.sem()
        elif y == 'skew':
            return x.skew()
        elif y == 'var':
            return x.var()
        else:
            raise ValueError('feature name error')
     
    def groupby_function(x):
        # x is a groupby dataframe

        # vars
        coor_x = x['x좌표'].iloc[0]
        coor_y = x['y좌표'].iloc[0]
        addr = x['지번주소'].iloc[0]
        house_type = x['지번주소'].iloc[0].split(' ')[-2]
        trade_type = x['지번주소'].iloc[0].split(' ')[-1]
        print(trade_type)
        built_year = int(x['건축년도'].iloc[0])
        print(built_year)
        unique_contract_dates = x['계약날짜'].unique()

        #
        df['distance_x'] = df['x좌표'] - coor_x
        df['distance_y'] = df['y좌표'] - coor_y
        df['distance'] = np.sqrt(df['distance_x']**2 + df['distance_y']**2)
        
        for target_range in ranges_list:

            range_df = df[
                (df['distance'] <= target_range)
                &(df['지번주소'] != addr)
                &(df['부동산유형'] == house_type)
                &(df['거래유형'] == trade_type)
                &(df['건축년도'] <= built_year)
                &(df['건축년도'] > (built_year - 5))
            ]
            
            #
            if range_df.shape[0] == 0:
                target_range_cols = [col for col in all_numerical_feature_cols if str(target_range) in col]
                
                i_list = []
                for i in range(x.shape[0]):
                    j_list = []
                    for j in range(len(target_range_cols)):
                        j_list.append(np.nan)
                    
                    i_list.append(j_list)
                
                nan_df = pd.DataFrame(np.array(i_list), columns=target_range_cols)
                
                return nan_df
            
            #
            else:
                
                for contract_date in unique_contract_dates:
                    contract_date = pd.to_datetime(contract_date)
                    
                    original_df = x[x['계약날짜'] == contract_date]
                    
                    contract_date_df = range_df[
                        (range_df['계약날짜'] <= contract_date)
                        &(range_df['계약날짜'] > (contract_date - pd.DateOffset(months=date_offset_months)))
                    ]
                    
                    if contract_date_df.shape[0] == 0:
                        target_range_cols = [col for col in all_numerical_feature_cols if str(target_range) in col]
                        
                        i_list = []
                        for i in range(original_df.shape[0]):
                            j_list = []
                            for j in range(len(target_range_cols)):
                                j_list.append(np.nan)

                            i_list.append(j_list)

                        nan_df = pd.DataFrame(np.array(i_list), columns=target_range_cols)
                        
                        x.loc[original_df.index, target_range_cols] = nan_df
                        #return nan_df
                    
                    
                    #
                    else:
                        
                        
                        for num_col in numerical_cols:
                            
                            for num_feat in numerical_description_features_list:
                                
                                feat_col_name = '최근{}개월_'.format(date_offset_months) + str(target_range) + '미터이내_' + num_col + '_' + num_feat
                                
                                try:
                                    x.loc[original_df.index, feat_col_name] = numerical_description_feature_creator(contract_date_df[num_col], num_feat)
                                except:
                                    x.loc[original_df.index, feat_col_name] = np.nan
                        
        return x[all_numerical_feature_cols]
    
    df[all_numerical_feature_cols] = df.groupby(['시군구', '지번', '건축년도', '부동산유형', '거래유형']).apply(groupby_function).reset_index(drop=True)
    
    return df

In [14]:
sample_df = main_data_df.sample(frac=0.01)
print(sample_df.shape)
sample_df.head()

(50068, 36)

,시군구,지번,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준,지번주소,토지일련번호,지목명,토지면적,용도지역명1,용도지역명2,토지이동상황,지형높이,지형형상,도로접면,데이터기준일자,distance_x,distance_y,distance
2737394,서울특별시 마포구 연남동,562-5,562,5,윤채,월세,35.91,7000,80,3,2014,연남로3길 58,연립다세대,1억4천 이하,윤채,기타,일반,대,192839.059795,450876.900578,2014-03-05,2985,서울특별시 마포구 연남동 562-5 2014 연립다세대 월세,34179,대,231.1,제2종일반주거지역,지정되지않음,다세대,평지,정방형,소로각지,2021-07-29,NaN,NaN,NaN
582821,서울특별시 강동구 천호동,449-49,449,49,힐탑프라자,월세,20.48,500,35,12,1994,천호대로 1073,오피스텔,1억4천 이하,힐탑프라자,기타,일반,대,211547.771781,448271.330094,2013-01-21,2577,서울특별시 강동구 천호동 449-49 1994 오피스텔 월세,25595,대,2315.0,일반상업지역,지정되지않음,업무용,평지,사다리형,광대세각,2021-07-29,NaN,NaN,NaN
3077283,서울특별시 서초구 서초동,1593-7,1593,7,서초이오빌,전세,45.96,25000,0,23,2003,효령로53길 45,아파트,24000~26000,서초이오빌,기타,일반,대,201066.999078,442700.742609,2017-01-06,4023,서울특별시 서초구 서초동 1593-7 2003 아파트 전세,24716,대,2896.6,일반상업지역,지정되지않음,상업기타,평지,부정형,세로각지(가),2021-07-29,NaN,NaN,NaN
2900432,서울특별시 서대문구 홍제동,136-10,136,10,목련빌라(136-10),매매,29.31,18500,0,4,2016,홍제원길 15-6,연립다세대,18000~20000,목련,기타,일반,대,195306.001192,453870.388340,2016-04-07,3749,서울특별시 서대문구 홍제동 136-10 2016 연립다세대 매매,10750,대,324.0,제3종일반주거지역,지정되지않음,다세대,평지,가로장방,세로한면(가),2021-07-29,NaN,NaN,NaN
881986,서울특별시 강서구 방화동,615-103,615,103,형제,전세,73.92,10000,0,5,1982,개화동로25길 39,아파트,1억4천 이하,형제,기타,일반,대,182969.778781,451533.506781,2016-11-17,3973,서울특별시 강서구 방화동 615-103 1982 아파트 전세,33543,대,3851.0,제2종일반주거지역,지정되지않음,아파트,평지,부정형,소로각지,2021-07-29,NaN,NaN,NaN

In [15]:
prac_df = temp_func(sample_df)
print(prac_df.shape)
prac_df.head()

UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (IMPORT_NAME) found

File "..\..\..\..\AppData\Local\Temp\ipykernel_17652\3598241349.py", line 3:
<source missing, REPL/exec in use?>