In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
font = {'size': 16}
matplotlib.rc('font', **font)
tqdm.tqdm.pandas()

In [2]:
%%time
main_data_df = pd.read_csv('./Prepped Data/main_data_coor_20211223.csv')
main_data_df = main_data_df.rename(columns={'글자':'대장구분명'})
main_data_df['대장구분명'] = main_data_df['대장구분명'].apply(lambda x: '산' if x == '산' else '일반')
print(main_data_df.shape)
main_data_df.head()

(5097504, 22)
Wall time: 13.4 s

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),계약년월,계약일,거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201101,5,35000,0,7.0,1988.0,언주로 103,아파트,34000~36000,개포현대,현대,일반,대,204626.688971,442141.82001
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201101,18,20000,0,8.0,1988.0,언주로 103,아파트,18000~20000,개포현대,현대,일반,대,204626.688971,442141.82001
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,1,24000,0,5.0,1988.0,언주로 103,아파트,22000~24000,개포현대,현대,일반,대,204626.688971,442141.82001
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,11,31000,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,24,30500,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001

In [3]:
main_data_df['계약년월'] = main_data_df['계약년월'].astype('str')

In [4]:
main_data_df['계약일'] = main_data_df['계약일'].astype('str').apply(lambda x: '0'+x if len(x) < 2 else x)

In [5]:
main_data_df.head()

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),계약년월,계약일,거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201101,05,35000,0,7.0,1988.0,언주로 103,아파트,34000~36000,개포현대,현대,일반,대,204626.688971,442141.82001
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201101,18,20000,0,8.0,1988.0,언주로 103,아파트,18000~20000,개포현대,현대,일반,대,204626.688971,442141.82001
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,01,24000,0,5.0,1988.0,언주로 103,아파트,22000~24000,개포현대,현대,일반,대,204626.688971,442141.82001
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,11,31000,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,201102,24,30500,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001

In [6]:
main_data_df['계약날짜'] = main_data_df['계약년월'] + main_data_df['계약일']

In [7]:
main_data_df['계약날짜'] = pd.to_datetime(main_data_df['계약날짜'], format='%Y%m%d')

In [9]:
main_data_df = main_data_df.drop(columns=['계약년월', '계약일'])
print(main_data_df.shape)
main_data_df.head()

(5097504, 21)

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,35000,0,7.0,1988.0,언주로 103,아파트,34000~36000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-01-05
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,20000,0,8.0,1988.0,언주로 103,아파트,18000~20000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-01-18
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,24000,0,5.0,1988.0,언주로 103,아파트,22000~24000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-01
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,31000,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-11
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,30500,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-24

In [14]:
main_data_df['계약날짜'].iloc[0]

Timestamp('2011-01-05 00:00:00')

In [11]:
dir(main_data_df['계약날짜'].iloc[0])

['__add__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__radd__',
 '__reduce__',
 '__reduce_cython__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__setstate_cython__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_date_repr',
 '_repr_base',
 '_round',
 '_short_repr',
 '_time_repr',
 'asm8',
 'astimezone',
 'ceil',
 'combine',
 'ctime',
 'date',
 'day',
 'day_name',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'dst',
 'floor',
 'fold',
 'freq',
 'freqstr',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'now',
 'quarter',
 'replace',
 'resolution',
 'round',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'to_datetime64',
 'to_julian_date',
 'to_numpy',
 'to_period',
 'to_pydatetime',
 'today',
 'toordinal',
 'tz',
 'tz_convert',
 'tz_localize',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'value',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [13]:
main_data_df['계약날짜'].iloc[0].value

1294185600000000000

In [35]:
(2011 * 365 + 31 + 5) *  24 * 60 * 60

63422006400

In [44]:
(main_data_df['계약날짜'].iloc[0] - pd.to_datetime('2006-01-01')).days

1830

In [39]:
main_data_df['계약날짜'].iloc[0]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'Timestamp'

In [46]:
main_data_df['계약날짜일수_2006년기준'] = (main_data_df['계약날짜'] - pd.to_datetime('2006-01-01')).dt.days

In [47]:
main_data_df.head()

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준
0,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,35000,0,7.0,1988.0,언주로 103,아파트,34000~36000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-01-05,1830
1,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,20000,0,8.0,1988.0,언주로 103,아파트,18000~20000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-01-18,1843
2,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,24000,0,5.0,1988.0,언주로 103,아파트,22000~24000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-01,1857
3,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,31000,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-11,1867
4,서울특별시 강남구 개포동,655-2,655,2,개포2차현대아파트(220),전세,77.75,30500,0,9.0,1988.0,언주로 103,아파트,30000~32000,개포현대,현대,일반,대,204626.688971,442141.82001,2011-02-24,1880

In [48]:
main_data_df = main_data_df.sort_values(['시군구', '본번', '부번', '건축년도', '계약날짜']).reset_index(drop=True)
print(main_data_df.shape)
main_data_df.head()

(5097504, 22)

,시군구,번지,본번,부번,건물/단지명,거래유형,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준
0,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,2253,12,12.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-02-22,4070
1,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,730,10,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-04-26,4133
2,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,1815,4,8.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2017-08-31,4260
3,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3865,17,11.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-03-29,4470
4,서울특별시 강남구 개포동,12,12,0,SH대치1단지아파트,월세,25.35,3062,7,9.0,1991.0,개포로109길 5,아파트,1억4천 이하,SH대치단지,기타,일반,대,206607.181143,443586.061143,2018-07-14,4577

In [50]:
negative_df = main_data_df[(main_data_df['거래/보증금(만원)'] < 0)|(main_data_df['월세(만원)'] < 0)]
print(negative_df.shape)
negative_df.head()

(0, 22)

Empty DataFrame
Columns: [시군구, 번지, 본번, 부번, 건물/단지명, 거래유형, 전용면적(㎡), 거래/보증금(만원), 월세(만원), 층, 건축년도, 도로명, 부동산유형, 가격범위, 건물단지명_키워드, 브랜드, 대장구분명, 지목, x좌표, y좌표, 계약날짜, 계약날짜일수_2006년기준]
Index: []

In [64]:
%%time
main_data_df.to_csv('./Prepped Data/main_data_coor_days_20211223.csv', index=False)

Wall time: 51.1 s