In [1]:
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
pd.options.mode.chained_assignment = None  # default='warn'
plt.rcParams['font.family'] = 'Malgun Gothic'
font = {'size': 16}
matplotlib.rc('font', **font)
tqdm.tqdm.pandas()

In [2]:
%%time
main_data_df = pd.read_csv('./Prepped Data/main_data_coor_days_nonan_20211224.csv', dtype={1:'str', 9:'Int64', 10:'Int64'})
main_data_df['계약날짜'] = pd.to_datetime(main_data_df['계약날짜'])
main_data_df = main_data_df[main_data_df['거래유형'] == '매매'].drop(columns=['거래유형']).reset_index(drop=True)
print(main_data_df.shape)
main_data_df.head()

(2091509, 21)
Wall time: 14.8 s

,시군구,번지,본번,부번,건물/단지명,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준
0,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,33.18,15900,0,1,1992,개포로109길 9,아파트,14000~16000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-03,2
1,서울특별시 강남구 개포동,12,12,0,삼익대청아파트,39.53,24800,0,5,1992,개포로109길 21,아파트,24000~26000,삼익대청,기타,일반,대,206607.181143,443586.061143,2006-01-07,6
2,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,12,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8
3,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,49.86,33300,0,11,1992,개포로109길 9,아파트,32000~34000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8
4,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,4,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-10,9

In [3]:
main_data_df['구'] = main_data_df['시군구'].apply(lambda x: x.split(' ')[1])
main_data_df['동'] = main_data_df['시군구'].apply(lambda x: x.split(' ')[2])

In [4]:
main_data_df['계약날짜일수_2006년기준'] = main_data_df['계약날짜일수_2006년기준'].astype('Int64')

In [5]:
main_data_df.isna().sum()

시군구               0
번지                0
본번                0
부번                0
건물/단지명            0
전용면적(㎡)           0
거래/보증금(만원)        0
월세(만원)            0
층                 0
건축년도              0
도로명               0
부동산유형             0
가격범위              0
건물단지명_키워드         0
브랜드               0
대장구분명             0
지목                0
x좌표               0
y좌표               0
계약날짜              0
계약날짜일수_2006년기준    0
구                 0
동                 0
dtype: int64

In [6]:
main_data_df['주소_건축년도'] = main_data_df['시군구'] + ' ' + main_data_df['번지'].astype('str') + ' ' + main_data_df['건축년도'].astype('str')

In [7]:
main_data_df.head()

,시군구,번지,본번,부번,건물/단지명,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준,구,동,주소_건축년도
0,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,33.18,15900,0,1,1992,개포로109길 9,아파트,14000~16000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-03,2,강남구,개포동,서울특별시 강남구 개포동 12 1992
1,서울특별시 강남구 개포동,12,12,0,삼익대청아파트,39.53,24800,0,5,1992,개포로109길 21,아파트,24000~26000,삼익대청,기타,일반,대,206607.181143,443586.061143,2006-01-07,6,강남구,개포동,서울특별시 강남구 개포동 12 1992
2,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,12,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992
3,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,49.86,33300,0,11,1992,개포로109길 9,아파트,32000~34000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992
4,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,4,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-10,9,강남구,개포동,서울특별시 강남구 개포동 12 1992

In [8]:
main_data_df['계약날짜'].nunique()

5808

In [10]:
def identify_bulk_trade(df):
    df = df.copy()
    
    df['일괄계약'] = np.nan
    
    for addr in tqdm.tqdm_notebook(df['주소_건축년도'].unique()):
        addr_df = df[df['주소_건축년도'] == addr]
        
        if addr_df['계약날짜'].nunique() == 1:
            df.loc[addr_df.index, '일괄계약'] = 'Y'
    
    return df

In [11]:
prac_df = identify_bulk_trade(main_data_df)

c:\users\max6296\ml\lib\site-packages\ipykernel_launcher.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`

  0%|          | 0/90539 [00:00<?, ?it/s]

In [27]:
main_data_df = prac_df.copy()
print(main_data_df.shape)
main_data_df.head()

(2091509, 25)

,시군구,번지,본번,부번,건물/단지명,전용면적(㎡),거래/보증금(만원),월세(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준,구,동,주소_건축년도,일괄계약
0,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,33.18,15900,0,1,1992,개포로109길 9,아파트,14000~16000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-03,2,강남구,개포동,서울특별시 강남구 개포동 12 1992,NaN
1,서울특별시 강남구 개포동,12,12,0,삼익대청아파트,39.53,24800,0,5,1992,개포로109길 21,아파트,24000~26000,삼익대청,기타,일반,대,206607.181143,443586.061143,2006-01-07,6,강남구,개포동,서울특별시 강남구 개포동 12 1992,NaN
2,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,12,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992,NaN
3,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,49.86,33300,0,11,1992,개포로109길 9,아파트,32000~34000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992,NaN
4,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,0,4,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-10,9,강남구,개포동,서울특별시 강남구 개포동 12 1992,NaN

In [28]:
main_data_df['일괄계약'].describe()

count     69741
unique        1
top           Y
freq      69741
Name: 일괄계약, dtype: object

In [29]:
main_data_df['일괄계약'].fillna('N', inplace=True)

In [30]:
main_data_df['일괄계약'].describe()

count     2091509
unique          2
top             N
freq      2021768
Name: 일괄계약, dtype: object

In [31]:
main_data_df['일괄계약'].value_counts()

N    2021768
Y      69741
Name: 일괄계약, dtype: int64

In [32]:
main_data_df['월세(만원)'].describe()

count    2091509.0
mean           0.0
std            0.0
min            0.0
25%            0.0
50%            0.0
75%            0.0
max            0.0
Name: 월세(만원), dtype: float64

In [33]:
main_data_df = main_data_df.drop(columns=['월세(만원)'])

In [34]:
main_data_df['계약날짜기준_건물연식'] = main_data_df['계약날짜'].dt.year - main_data_df['건축년도']

In [35]:
def year_circular_sine_func(x):
    return np.sin(2*np.pi*((x)/365))

def year_circular_cosine_func(x):
    return np.cos(2*np.pi*((x)/365))

In [36]:
main_data_df['계약날짜일수_sin'] = main_data_df['계약날짜일수_2006년기준'].apply(year_circular_sine_func)
main_data_df['계약날짜일수_cos'] = main_data_df['계약날짜일수_2006년기준'].apply(year_circular_cosine_func)

In [37]:
main_data_df.head()

,시군구,번지,본번,부번,건물/단지명,전용면적(㎡),거래/보증금(만원),층,건축년도,도로명,부동산유형,가격범위,건물단지명_키워드,브랜드,대장구분명,지목,x좌표,y좌표,계약날짜,계약날짜일수_2006년기준,구,동,주소_건축년도,일괄계약,계약날짜기준_건물연식,계약날짜일수_sin,계약날짜일수_cos
0,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,33.18,15900,1,1992,개포로109길 9,아파트,14000~16000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-03,2,강남구,개포동,서울특별시 강남구 개포동 12 1992,N,14,0.034422,0.999407
1,서울특별시 강남구 개포동,12,12,0,삼익대청아파트,39.53,24800,5,1992,개포로109길 21,아파트,24000~26000,삼익대청,기타,일반,대,206607.181143,443586.061143,2006-01-07,6,강남구,개포동,서울특별시 강남구 개포동 12 1992,N,14,0.103102,0.994671
2,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,12,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992,N,14,0.137279,0.990532
3,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,49.86,33300,11,1992,개포로109길 9,아파트,32000~34000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-09,8,강남구,개포동,서울특별시 강남구 개포동 12 1992,N,14,0.137279,0.990532
4,서울특별시 강남구 개포동,12,12,0,성원대치2단지아파트,39.53,24700,4,1992,개포로109길 9,아파트,24000~26000,성원대치단지,기타,일반,대,206607.181143,443586.061143,2006-01-10,9,강남구,개포동,서울특별시 강남구 개포동 12 1992,N,14,0.154309,0.988023

In [38]:
main_data_df['지목'].value_counts()

대    2083425
임       2554
전       1804
도       1691
장        870
잡        413
답        311
주        148
차        110
공         84
종         63
창         18
수         14
사          4
Name: 지목, dtype: int64

In [39]:
main_data_df.dtypes

시군구                       object
번지                        object
본번                         int64
부번                         int64
건물/단지명                    object
전용면적(㎡)                  float64
거래/보증금(만원)                 int64
층                          Int64
건축년도                       Int64
도로명                       object
부동산유형                     object
가격범위                      object
건물단지명_키워드                 object
브랜드                       object
대장구분명                     object
지목                        object
x좌표                      float64
y좌표                      float64
계약날짜              datetime64[ns]
계약날짜일수_2006년기준             Int64
구                         object
동                         object
주소_건축년도                   object
일괄계약                      object
계약날짜기준_건물연식                Int64
계약날짜일수_sin               float64
계약날짜일수_cos               float64
dtype: object

In [40]:
cat_cols = ['부동산유형', '브랜드', '대장구분명', '지목', '구', '동', '일괄계약']

In [41]:
for col in tqdm.tqdm_notebook(cat_cols):
    unique_cats = main_data_df[col].unique()
    
    # mapping
    cat_map = {}
    for i, v in enumerate(unique_cats):
        cat_map[v] = i
        
    main_data_df[col] = main_data_df[col].map(cat_map)
    
    map_df = pd.DataFrame(cat_map, index=[0])
    map_df.to_excel('./Training/Training5_20220204/cat_col_maps/{}'.format(col+'.xlsx'), index=False)

c:\users\max6296\ml\lib\site-packages\ipykernel_launcher.py:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """Entry point for launching an IPython kernel.

  0%|          | 0/7 [00:00<?, ?it/s]

In [42]:
training_data_df = main_data_df[[
    '주소_건축년도', '건축년도', '전용면적(㎡)', '층', 'x좌표', 'y좌표', '계약날짜일수_2006년기준', '계약날짜기준_건물연식',
    '계약날짜일수_sin', '계약날짜일수_cos'
] + cat_cols + ['거래/보증금(만원)']]
print(training_data_df.shape)
training_data_df.head()

(2091509, 18)

,주소_건축년도,건축년도,전용면적(㎡),층,x좌표,y좌표,계약날짜일수_2006년기준,계약날짜기준_건물연식,계약날짜일수_sin,계약날짜일수_cos,부동산유형,브랜드,대장구분명,지목,구,동,일괄계약,거래/보증금(만원)
0,서울특별시 강남구 개포동 12 1992,1992,33.18,1,206607.181143,443586.061143,2,14,0.034422,0.999407,0,0,0,0,0,0,0,15900
1,서울특별시 강남구 개포동 12 1992,1992,39.53,5,206607.181143,443586.061143,6,14,0.103102,0.994671,0,0,0,0,0,0,0,24800
2,서울특별시 강남구 개포동 12 1992,1992,39.53,12,206607.181143,443586.061143,8,14,0.137279,0.990532,0,0,0,0,0,0,0,24700
3,서울특별시 강남구 개포동 12 1992,1992,49.86,11,206607.181143,443586.061143,8,14,0.137279,0.990532,0,0,0,0,0,0,0,33300
4,서울특별시 강남구 개포동 12 1992,1992,39.53,4,206607.181143,443586.061143,9,14,0.154309,0.988023,0,0,0,0,0,0,0,24700

In [43]:
training_data_df['x좌표'] = training_data_df['x좌표'] / 100000
training_data_df['y좌표'] = training_data_df['y좌표'] / 100000

In [44]:
training_data_df.head()

,주소_건축년도,건축년도,전용면적(㎡),층,x좌표,y좌표,계약날짜일수_2006년기준,계약날짜기준_건물연식,계약날짜일수_sin,계약날짜일수_cos,부동산유형,브랜드,대장구분명,지목,구,동,일괄계약,거래/보증금(만원)
0,서울특별시 강남구 개포동 12 1992,1992,33.18,1,2.066072,4.435861,2,14,0.034422,0.999407,0,0,0,0,0,0,0,15900
1,서울특별시 강남구 개포동 12 1992,1992,39.53,5,2.066072,4.435861,6,14,0.103102,0.994671,0,0,0,0,0,0,0,24800
2,서울특별시 강남구 개포동 12 1992,1992,39.53,12,2.066072,4.435861,8,14,0.137279,0.990532,0,0,0,0,0,0,0,24700
3,서울특별시 강남구 개포동 12 1992,1992,49.86,11,2.066072,4.435861,8,14,0.137279,0.990532,0,0,0,0,0,0,0,33300
4,서울특별시 강남구 개포동 12 1992,1992,39.53,4,2.066072,4.435861,9,14,0.154309,0.988023,0,0,0,0,0,0,0,24700

In [45]:
%%time
training_data_df.to_csv('./Prepped Data/training_data_20220204_2.csv', index=False)

Wall time: 10.7 s